### PR TITLE
NET-2519: Added foot to pay rate units

### PR DESCRIPTION
**Pull request by nick-rigup**
Requested in On Call Support request,
Discussion in slack. SIgn off by Luke T.

Screen Shot 2020-07-15 at 3 17 39 PM

### CODE REVIEW

**Comment by alxyuu** [comment]
you're not supposed to commit directly to cocs tickets but code looks fine

**Comment by nick-rigup** [comment]
👍  I thought I remember something about that, thought I'd give it a whirl

**Comment by nick-rigup** [comment]
Thanks!

**Comment by nick-rigup** [comment]
Is that still running in codeship?

**Pull request merged**
